# Site settings
title: Jeremy Pry Resume
description: A resume template for Jekyll and GitHub Pages sites.
baseurl: /

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - README.md
  - Gemfile*
  - index.html

# Resume settings
resume_avatar: 84552f74b71a1a3e6aae380aa9ab3bd3
resume_name: Jeremy Pry
resume_title: WordPress Developer
resume_contact_email: resume@jpry.com
resume_header_contact_info: "Downingtown, PA | 484.693.0789 | resume@jpry.com"
resume_header_intro: >
  WordPress and Web Developer with expertise in WordPress best practices,
  general development design practices, and experience working as part of a distributed development team.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: 'yes'

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       false
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:  https://github.com/JPry
  resume_twitter_url: http://twitter.com/JPry
#  resume_facebook_url: https://facebook.com/jeremy.pry
  resume_linkedin_url: https://www.linkedin.com/in/jeremypry/
  resume_instagram_url: https://www.instagram.com/jpry/
  resume_website_url: http://jeremypry.com/
resume_print_social_links: false

# Design settings
resume_theme: default

# Defaults
defaults:
    -
        scope:
            path: ""
        values:
            layout: "resume"
